
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

wake_on_lan:

webostv:
  host: 192.168.25.14
  name: Living Room TV
  turn_on_action:
    service: wake_on_lan.send_magic_packet
    data:
      mac: "58:fd:b1:82:da:9e"
  customize:
    sources:
      - livetv
      - youtube
      - netflix

media_player:

notify:

homeassistant:
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 127.0.0.1
      allow_bypass_login: true
    - type: homeassistant
